// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://exfpgnrjcwnhdqkpwwwj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV4ZnBnbnJqY3duaGRxa3B3d3dqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5MzYyODAsImV4cCI6MjA1NzUxMjI4MH0.NpHPtXI-oqrcAVah1J9wkLC0FEM7wmHnlAjuWSbiHB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);